### ISSUE TITLE
Compiler bug?

### ISSUE THREAD

**Issue by mbrodersen** [valderman/haste-compiler#289]
Hi,

I today updated Haste to latest. Unfortunately this introduced a strange bug deep in my code that looks very odd. In the following code, (buttonDown w) will be False in the code *above* the "where" and False in the code *below* the "where". Which should not be possible. I get the following output when releasing the mouse button, hovering the mouse over the widget button:

	[Debug "Handling MouseUp [False]",Ignore,Debug "True",...]

Notice that (buttonDown w) is both False and True at the same time :-/

	updateWidget :: (Eq id,Show id) => Event -> Widget id -> ([WidgetEvent id],Widget id)
	
	updateWidget e (ButtonWidget w) =
	case e of
		MouseDown xy 0 ->
			(ignoreMaybe xy, ButtonWidget w { buttonDown = isHit xy })

		MouseMove xy ->
			if buttonDown w && not (isHit xy) then
				(ignoreMaybe xy, ButtonWidget w { buttonDown = False })
			else
				(ignoreMaybe xy, ButtonWidget w)

		MouseUp xy 0 ->
			if buttonDown w then
				([WidgetClicked $ buttonId w], ButtonWidget w { buttonDown = False })
			else
				([Debug $ "Handling MouseUp [" ++ show (buttonDown w) ++ "]"] ++ ignoreMaybe xy, ButtonWidget w)

		_ -> ([], ButtonWidget w)

	where
		ignoreMaybe xy = if isHit	xy then [Ignore, Debug $ show $ buttonDown w, Debug $ show e, Debug $ show w] else []

		isHit (x,y) = box2IsHit (V2 x y) (buttonBox w)

**Comment by mbrodersen** [comment]
OK I narrowed it down to this:

In the following code, (if buttonDown w then ... else) will (incorrectly) take the "else" path when releasing mouse button:

		MouseUp xy 0 ->
			if buttonDown w then
				([WidgetClicked $ buttonId w], ButtonWidget w { buttonDown = False })
			else
				...

And this slightly modified code will take the correct "then" path when doing the *exact* same actions:

		MouseUp xy 0 ->
			if buttonDown w then
				([WidgetClicked $ buttonId w, Debug $ show w], ButtonWidget w { buttonDown = False })
			else
				...

The only difference is that w is used in the "then" part. In other words, it looks as if there is a bug in the compiler variable flow analysis?

**Comment by valderman** [comment]
Does the issue persist if you compile with `--ddisable-js-opts`? It's most likely related to either the slightly modified compilation scheme for case expressions, or the related optimizations introduced at the same time.

**Comment by mbrodersen** [comment]
Yep it works if it compile with --ddisable-js-opts. So you are on the right track :-)

**Comment by valderman** [comment]
By the way, which exact commit did you find the bug in? 2880436 disables an incorrect optimization which caused somewhat similar effects, but I assume you're using a later revision?

**Comment by mbrodersen** [comment]
I am away from my computer at the moment. However I checked out latest last
night Melbourne Australia time. So about 14 hours ago from this email.

**Comment by mbrodersen** [comment]
I just updated to latest again (add0b6174a). And the bug is still there. Unless I used the --ddisable-js-opts option.

**Comment by valderman** [comment]
Do you have some kind of complete test case which isn't too big that I could use to test this? I have a pretty good idea what optimization is causing it, but I don't really have a way to trigger the bug ATM.

**Comment by mbrodersen** [comment]
The application is fairly big unfortunately. I will try and narrow it down to a simpler test case. Can you give me hints as to what you think it is? I am (btw) the maintainer of a JIT compiler for a Haskell-like functional programming language at work. So you are welcome to use compiler speak when describing what you think the bug could be.

**Comment by valderman** [comment]
Is this bug still present as of 0.5? Optimizations in particular have received a pretty big overhaul so the odds are good that it got fixed even though I couldn't reproduce it.

**Comment by mbrodersen** [comment]
I first installed haste-0.5.0 and built the code using the same options as before. It crashes at runtime (in the browser) with the following errors:

Uncaught ReferenceError: _4m8 is not defined

and a large numbe of:

uncaught TypeError: Cannot read property '0' of undefined

I then tried to compile using the following options:

--opt-whole-program --opt-all --opt-unsafe-ints

and I get:

Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
hastec: user error (Couldn't execute Google Closure compiler: Command 'java' failed with error  code 130)

This is code that compile/run OK with a previous version of Haste.

**Comment by valderman** [comment]
Would this application happen to be open source? With source access, tracking down the bug would probably be fairly easy using `git bisect` even without a more minimal example.

**Comment by valderman** [comment]
As for the Closure issue, does unsetting `JAVA_TOOL_OPTIONS` as suggested in http://stackoverflow.com/questions/26074446/picked-up-java-tool-options-javaagent-usr-share-java-jayatanaag-jar-when-st help?

**Comment by mbrodersen** [comment]
Unfortunately not. However I might be able to narrow down the code to parts
I can share (while still demonstrating the problem). Will investigate.

**Comment by valderman** [comment]
Good news; some tests fail with similar symptoms when building with GHC 7.10. With a bit of luck, this may turn out to be the same bug.

**Comment by mbrodersen** [comment]
Yes that is indeed good news :-)

May the Luck be With You ;-)

**Comment by valderman** [comment]
The mystery is (hopefully) solved: some time between 0.4 and 0.5, the code generated for evaluation of thunks changed in such a way that some values would in some rare cases get overwritten by garbage as during evaluation. Will be pushing a fix shortly.

**Comment by mbrodersen** [comment]
That seems to match my experience of when the bug appeared. Crossing
fingers :-)

**Comment by valderman** [comment]
OK, so the problem should be fixed on master now. More specifically, the RTS would blackhole non-updatable thunks, which was fine for single entry ones but distinctly not fine for non-updatable yet reentrant thunks.

**Comment by mbrodersen** [comment]
Excellent. I will take it for a spin :-)

**Comment by mbrodersen** [comment]
Good, bad and good news :-)

The good news is that I can compile the latest haste-compiler (0.5.1.0) on Linux 15.04. That never worked before. Excellent.

The bad news is that running the application (with and without --ddisable-js-opts) gives the errors:

1 x Uncaught ReferenceError: _54J is not defined
N x Uncaught TypeError: Cannot read property '0' of undefined

The good news is that the two builds (with and without --ddisable-js-opts) now behaves identically :-) (before it would fail in different ways).

I will try and reduce the application to a "minimum code to fail" test case.

**Comment by valderman** [comment]
Ah, I thought I had solved it for sure this time.

I don't know if this is useful to you, but as of 946cbbf483799c92be067411e761d1497a089f7f, the `--debug` option is slightly more helpful, using mangled Haskell names in the generated code instead of the usual short ones. This should help give more informative stack traces. It also annotates all external functions with '/* EXTERNAL */', making them a bit easier to check on. This is kind of useful since foreign interaction is often where bugs happen in my experience.

**Comment by valderman** [comment]
So, Haste 0.5.2 fixes no less than four different bugs which may result in symptoms like these, and the current master fixes yet another (hypothetical) one. Is the problem fixed as of 9074a934a13bdf9cd35336caa1372292148e5d91?

**Comment by mbrodersen** [comment]
Hi Anton,

I am trying out latest (Haste 0.5.3) to see if the bug(s) are fixed.
However I am getting this new compile error:

    Unacceptable result type in foreign declaration: IO Elem
    When checking declaration:
      foreign import ccall safe "static _jsImageToImageRGB"
_jsImageToImageRGB
        :: JSString -> Double -> Double -> Double -> JSString -> IO Elem

for this Haskell declaration:

foreign import ccall _jsImageToImageRGB :: JSString -> Double -> Double ->
Double -> JSString -> IO Elem

Which compiled OK with previous versions of Haste.

Please advise? I need that function to work to test the rest.

Thanks
Morten

**Comment by valderman** [comment]
The data constructor for `Elem` was accidentally removed from the export list of Haste.DOM/Haste.DOM.JSString. This went undiscovered since most (preferably all) code should really be using `Haste.Foreign` (which is both faster and more flexible) instead of the vanilla FFI. I've added the export back for `Elem` in f1d7184 so it is now usable with the vanilla FFI as well.

If you run into similar problems for `JSString` or `JSAny`, their respective data constructors are now exported from `Haste.Prim` which has been moved into the `haste-prim` package.

**Comment by mbrodersen** [comment]
Thanks. That fixed the problem. Here is the next one:

I am using loadBitmap (in Canvas.hs) to load bitmaps and draw (in Canvas.hs) to draw them. This has worked fine in the past, but now I am getting the following runtime errors:

Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'

All I am doing is loadBitmap() followed by draw().

**Comment by valderman** [comment]
That's strange; I can't seem to reproduce that. The following example loads and executes fine, regardless of compilation flags:

    import Haste
    import Haste.DOM
    import Haste.Graphics.Canvas
    
    main = setTimer (Once 1000) $ do
      can <- createCanvas 1000 1000 `with` [style "border" =: "1px solid black"]
      appendChild documentBody can
      bmp <- loadBitmap "http://ekblad.cc/kungen.jpg"
      render can $ draw bmp (100, 100)

Removing the timer simply renders nothing (since the image hasn't finished loading by the time of the `draw` call), but doesn't crash. Does this example work on your side? If it does, I suspect that the original problem is still there and simply moved to your drawing code with the new fixes.

**Comment by mbrodersen** [comment]
I have worked on tracking down the bug. Here is what I have found so far. In this code:

    handleRpy :: Maybe String -> App DomainEvent
    handleRpy rpyMaybe = do
     	liftIO $ jsLog $ "[handleRpy] rpyMaybe " ++ show rpyMaybe
    	case rpyMaybe of
    		Nothing	 -> onError "Error calling server"
    		Just rpy -> do
    			liftIO $ jsLog $ "[handleRpy] Match: Just rpy"
    			case reads rpy of
    				[(Error s,_)]									-> (liftIO $ jsLog "[handleRpy] case (Error, ...)") >> onError s
    				[(SVGUploadRpy (Left s),_)]		-> (liftIO $ jsLog "[handleRpy] case SVGUploadRpy") >> onError s
    				[(e, _)]											-> (liftIO $ jsLog "[handleRpy] case (e, _)") >> return e
    				_															-> (liftIO $ jsLog "[handleRpy] case _") >> (return $ Error "Error decoding server reply")
    	where
    		onError s = liftIO (jsAlert $ "Server: " ++ s) >> return (Error s)

The bug is triggered in this line:

    case reads rpy of

Here is the browser log:

    [handleRpy] rpyMaybe Just "LoginRpy (Just (SId \"vO88x887TdL0MI0u\",User ..." (long string reduced here)
    [handleRpy] Match: Just rpy
    [handleRpy] case reads
    Uncaught ReferenceError: _4KU is not defined
    [handleRpy] case reads
    Uncaught Infinite loop!
    [handleRpy] case reads
    Uncaught Infinite loop!

**Comment by mbrodersen** [comment]
More notes:

(Using Haste 0.5.3)

handleRpy is running in the following "App" monad. This monad (and the previous code) works perfectly fine in Haste 0.5.0, GHC and also in Haste 0.5.3 for a login page (before hitting the bug).

    {-# LANGUAGE BangPatterns #-}
    
    module MB.App.AIO where
    
    import Control.Applicative
    import Control.Monad.IO.Class

    data AIO i o m a =
    		AIO			(m (AIO i o m a))
    	|	AIORecv		(i -> AIO i o m a)
    	|	AIOReturn	a
    	|	AIOSend		o (AIO i o m a)
    
    ---------------------------------------------------------------------
    
    instance Monad m => Functor (AIO i o m) where
    	fmap !f (AIO		!io)		= AIO $ io >>= \(!aio) -> return $ fmap f aio
    	fmap !f (AIORecv	!k)		= AIORecv $ \(!i) -> fmap f (k i)
    	fmap !f (AIOReturn	!a)		= AIOReturn (f a)
    	fmap !f (AIOSend	!o !k)	= AIOSend o $ fmap f k
    
    ---------------------------------------------------------------------
    
    instance Monad m => Applicative (AIO i o m) where
    	pure !a = AIOReturn a
    
    	(AIO			!io)		<*> (!aio1) = AIO $ io >>= \(!aio0) -> return $ aio0 <*> aio1
    	(AIORecv		!k)		<*> (!aio1) = AIORecv $ \(!i) -> (k i) <*> aio1
    	(AIOReturn	!f)		<*> (!aio1) = fmap f aio1
    	(AIOSend		!o !k)	<*> (!aio1) = AIOSend o $ k <*> aio1
    
    ---------------------------------------------------------------------
    
    instance Monad m => Monad (AIO i o m) where
    	return !a = AIOReturn a
    
    	(AIO			!k)		>>= (!aio1) = AIO $ k >>= \(!aio0) -> return (aio0 >>= aio1)
    	(AIORecv		!k)		>>= (!aio1) = AIORecv $ \(!i) -> (k i) >>= aio1
    	(AIOReturn	!a)		>>= (!aio1) = aio1 a
    	(AIOSend		!o !k)	>>= (!aio1) = AIOSend o $ k >>= aio1
    
    ---------------------------------------------------------------------
    
    recv :: AIO i o m i
    recv = AIORecv $ \(!i) -> AIOReturn i
    
    ---------------------------------------------------------------------

    send :: o -> AIO i o m ()
    send !o = AIOSend o $ AIOReturn ()
    
    ---------------------------------------------------------------------
    
    -- run AIO as far as possible with no events
    
    runAIO :: MonadIO m => AIO i o m a -> m (AIO i o m a)
    runAIO (AIO !m) =
    	m >>= \(!aio) -> runAIO aio
    
    runAIO !aio =
    	return aio
    
    ---------------------------------------------------------------------
    
    -- run AIO as far as possible with one events
    
    runAIO1 :: MonadIO m => i -> AIO i o m a -> m (AIO i o m a)
    
    runAIO1 !i (AIO !m) =
    	m >>= runAIO1 i
    
    runAIO1 !i (AIORecv !k) =
    	runAIO (k i)
    
    runAIO1 _ !aio =
    	return aio
    
    ---------------------------------------------------------------------
    
    -- run AIO as far as possible with a number of events
    
    runAION :: MonadIO m => [i] -> AIO i o m a -> m (AIO i o m a)
    
    runAION !ix (AIO !m) =
    	m >>= runAION ix
    
    runAION !ix aio@(AIORecv !k) =
    	case ix of
    		[]		-> return aio
    		!(i:(!ix'))	-> runAION ix' (k i)
    
    runAION _ !aio =
    	return aio
    
    ---------------------------------------------------------------------
    
    waitForever :: Monad m => AIO i o m a
    waitForever = do
    	e <- recv
    	case e of
    		_	-> waitForever

**Comment by valderman** [comment]
What does the JS function where the crash happens look like when compiled with `--debug`? Could you recompile with `--debug` run the example until the crash happens, then just look up the line where it happens and post the enclosing function? Looking at the generated JS may give a hint as to what part is acting up.

**Comment by mbrodersen** [comment]
With --debug enabled, the log is now:

    [handleRpy] rpyMaybe Just "LoginRpy (Just (SId \"3C6xj8H55eZ06b31\",User ..."
    [handleRpy] Match: Just rpy
    Uncaught ReferenceError: _4KS is not defined
    [handleRpy] Match: Just rpy
    Uncaught Infinite loop!
    [handleRpy] Match: Just rpy
    Uncaught Infinite loop!

=> the uncaught reference error is now _4KS (not _4KU).

The "Uncaught reference error" happens in this function:

    _4KM/* $wa2 */ = function(_4KN/* s6XlP */, _4KO/* s6XlQ */){
      var _4KP/* s6XlR */ = function(_4KQ/* s6XlT */, _4KR/* s6XlU */){
        return new F(function(){return _4KS/* s6XlS */(_4KR/* s6XlU */);});
      },
      _4KT/* s6XlV */ = _4KO/* s6XlQ */;
      return new F(function(){return _4yG/* Text.ParserCombinators.ReadP.$fMonadPlusP_$cmplus */(new T1(1,B(_4Kt/* GHC.Read.$wa3 */(_4KN/* s6XlP */, _4KT/* s6XlV */))), new T(function(){
        return new T1(1,B(_4Kt/* GHC.Read.$wa3 */(_4KP/* s6XlR */, _4KT/* s6XlV */)));
      }));});
    },

In this line:

    return new F(function(){return _4KS/* s6XlS */(_4KR/* s6XlU */);});

I did a search for _4KS in the full .js file and it is not there. I did however find quite a few references to _4Ks. Not sure if this is important or not.

**Comment by mbrodersen** [comment]
Just in case: here is the haste implementation of the AIO monad I showed earlier. Other implementations work for console, graphics etc.

    module MB.App.AIO.Browser.Haste where
    
    import Data.IORef
    
    import MB.App.AIO
    import MB.App.AIO.Browser
    
    import MB.Haste.Event
    import MB.Haste.Setup
    
    import MB.Haste.Ajax
    import MB.Haste.JS.JS
    
    ---------------------------------------------------------------------
    
    newtype AppCB a = AppCB (IORef (App a))
    
    instance CB (AppCB a) where
    	callback = runHasteCB
    
    ---------------------------------------------------------------------
    
    runHaste :: App a -> IO ()
    runHaste app = do
    	refApp <- newIORef app
    	setup (AppCB refApp)
    
    ---------------------------------------------------------------------
    
    runHasteCB :: Event -> AppCB a -> IO (AppCB a)
    
    runHasteCB event appCB = do
    	runHasteCB1 (Just event) appCB
    
    ---------------------------------------------------------------------
    
    runHasteCB1 :: Maybe Event -> AppCB a -> IO (AppCB a)
    runHasteCB1 eventMaybe appCB@(AppCB refApp) = do
    	jsLog $ "[runHasteCB1] eventMaybe [" ++ show eventMaybe ++ "]"
    	app <- readIORef refApp
    	jsLog $ "[runHasteCB1] => app"
    	case app of
    		AIO m -> do
    			jsLog $ "[runHasteCB1] => AIO"
    			app' <- m
    			writeIORef refApp app'
    			runHasteCB1 eventMaybe appCB
    
    		AIORecv ik -> do
    			jsLog $ "[runHasteCB1] => AIORecv ik [" ++ show ik ++ "]"
    			case eventMaybe of
    				Nothing			-> return appCB
    				Just event	-> do
    					writeIORef refApp (ik event)
    					runHasteCB1 Nothing appCB
    
    		AIOReturn _ ->
    			jsLog $ "[runHasteCB1] => AIOReturn"
    			return appCB
    
    		AIOSend (Callback f) k -> do
    			jsLog $ "[runHasteCB1] => AIOSend"
    			writeIORef refApp k
    			f $ \s -> do
    				--jsAlert $ "[runHasteCB1] Callback [" ++ s ++ "]"
    				_ <- runHasteCB (ServerRpy (Just s)) appCB
    				return ()
    			runHasteCB1 eventMaybe appCB
    
    		AIOSend	(ServerReq c) k -> do
    			jsLog $ "[runHasteCB1] => ServerReq c [" ++ show c ++ "]"
    			writeIORef refApp k
    			callServerPOST "/event" c $ \rpyMaybe -> runHasteCB (ServerRpy rpyMaybe) appCB >> return ()
			runHasteCB1 eventMaybe appCB
    
    		_ -> do
    			jsLog $ "[runHasteCB1] => NO MATCH!"

**Comment by mbrodersen** [comment]
Good news. I upgraded to latest Haste (0.5.4.2) and the bug is fixed :-) It even works when I don't use the --ddisable-js-opts flag. It is also running significantly faster. Nice!

**Comment by valderman** [comment]
Great! I'm a little bit concerned that I still have no idea what fixed it (unless it was still broken in 0.5.4.1, then I have a pretty good idea), but fixed is fixed I guess.

**Comment by mbrodersen** [comment]
Yeah I know what you mean. It would be better to know what it is. However I
am happy I can be up-to-date with Haste now.
